[package]
name = "advent-of-code-rs"
version = "2019.2.2"
authors = ["Matthew Salazar <m@tthewsalazar.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "~2.33"